name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Asegúrate de que tu rama se llame main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        # Hemos quitado la línea "version: 10" para que no haya conflicto          

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Esto arregla el error "Node.js v20 is not supported"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Astro guarda el resultado aquí

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4